### ISSUE TITLE
Standard Format For Jfrog to Heimdall Tool

### ISSUE THREAD

**Issue by lbrowne2** [mitre/heimdall_tools#113]
I have been attempting to use the aforementioned jfrog conversion functionality in this tool; however, the vulnerability reports that I have been putting into them do not work. Is there a sample or standard format available to see where this error is? As it confidential information about the company that I work for I am not able to share any of the samples I have been using.

**Comment by Amndeep7** [comment]
Hi @lbrowne2, sorry for delay in responding - we've been busy with transitioning our tools, including heimdall_tools, to typescript, which is a process that has mostly finished.  The transitioned tool is available at https://github.com/mitre/saf.  If you're still having issues, please create a new issue there.
