### ISSUE TITLE
xccdf_results_mapper undefined method `match'

### ISSUE THREAD

**Issue by ccoffin** [mitre/heimdall_tools#120]
Trying to convert some OpenSCAP produced XCCDF results XML into HDF using xccdf_results_mapper on two different systems and have received the following error message in each case.

[number6@localhost Documents]$ sudo docker run -it -v $(pwd):/share mitre/heimdall_tools xccdf_results_mapper -x rhel7scap_2.xml -o hdf_results.json
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
Traceback (most recent call last):
	13: from /usr/local/bundle/bin/heimdall_tools:23:in `<main>'
	12: from /usr/local/bundle/bin/heimdall_tools:23:in `load'
	11: from /usr/local/bundle/gems/heimdall_tools-1.3.48.1.g88bd047/exe/heimdall_tools:14:in `<top (required)>'
	10: from /usr/local/bundle/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	 9: from /usr/local/bundle/gems/heimdall_tools-1.3.48.1.g88bd047/lib/heimdall_tools/command.rb:44:in `dispatch'
	 8: from /usr/local/bundle/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	 7: from /usr/local/bundle/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	 6: from /usr/local/bundle/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	 5: from /usr/local/bundle/gems/heimdall_tools-1.3.48.1.g88bd047/lib/heimdall_tools/cli.rb:49:in `xccdf_results_mapper'
	 4: from /usr/local/bundle/gems/heimdall_tools-1.3.48.1.g88bd047/lib/heimdall_tools/xccdf_results_mapper.rb:117:in `to_hdf'
	 3: from /usr/local/bundle/gems/heimdall_tools-1.3.48.1.g88bd047/lib/heimdall_tools/xccdf_results_mapper.rb:117:in `each_with_index'
	 2: from /usr/local/bundle/gems/heimdall_tools-1.3.48.1.g88bd047/lib/heimdall_tools/xccdf_results_mapper.rb:117:in `each'
	 1: from /usr/local/bundle/gems/heimdall_tools-1.3.48.1.g88bd047/lib/heimdall_tools/xccdf_results_mapper.rb:132:in `block in to_hdf'
/usr/local/bundle/gems/heimdall_tools-1.3.48.1.g88bd047/lib/heimdall_tools/xccdf_results_mapper.rb:93:in `satisfies_parse': undefined method `match' for #<Hash:0x00007f20ff9810d0> (NoMethodError)

**Comment by aaronlippold** [comment]
It's possible the actual file that producing the error would also be useful if you could attach it￼

**Comment by ccoffin** [comment]
Ah yes... here you go.

[rhel7scap_2.zip](https://github.com/mitre/heimdall_tools/files/7530584/rhel7scap_2.zip)
