### ISSUE TITLE
When executing ZAP mapper ./lib/data/cwe-nist-mapping.csv can not be found

### ISSUE THREAD

**Issue by SpeedieBe** [mitre/heimdall_tools#17]
I was not able to execute the zap mapper to convert to HDF without getting an error message saying  ./lib/data/cwe-nist-mapping.csv can not be found. I was able to to successfully run the zap mapper but only by being in the lib directory of the gem itself.  There might be an error with the gem load path.

**Comment by aaronlippold** [comment]
Hi, odd bug at the moement - where the relative path for the data is not being set correct after the gem install. It works if I clone it and run it locally but I will have our guys look at it and see if we can resolve the bug which I think is in the .gemspec file or in the 'requires' for the data loading

**Comment by Bialogs** [comment]
We should take a look at the way we are loading our files from `lib/`

Statements like this: `RESOURCE_DIR = Pathname.new(__FILE__).join('../../data')` using relative paths can be dangerous and may not always grab the correct file since they have to do with invocation location.

**Comment by rx294** [comment]
Fixed in #42

**Comment by rx294** [comment]
Hey @Bialogs if am not mistaken ```RESOURCE_DIR = Pathname.new(__FILE__).join('../../data')``` goes by relative location of the source code ...not the invocation location... and the gem does run from any location with this code...

if you still think it should be changed what do you think about
`RESOURCE_DIR = "#{File.dirname __dir__}/data"` ?

**Comment by Bialogs** [comment]
`__FILE__` should be the relative location to the particular file from the invocation location so you'd need to do a `File.expand_path(__FILE__)` to get the absolute location to where the gem is installed and then use that for the RESOURCE_DIR.

**Comment by rx294** [comment]
this issue fixed by https://github.com/mitre/heimdall_tools/pull/42;  
Pathname.new method revolves the absolute path and hence works as a gem
