### ISSUE TITLE
Output in evaluation format, not profile 

### ISSUE THREAD

**Issue by ejaronne** [mitre/heimdall_tools#2]
Currently fortify mapper formats the data as if it were a profile listing, because the data is all fails, no passes. Instead, recommend normal evaluation format, which will allow access to the SSP and CAAT functions in heimdall.

**Comment by rx294** [comment]
This issue has been fixed by https://github.com/mitre/heimdall_tools/pull/3 
and https://github.com/mitre/heimdall-lite/commit/2a145eb604946e79e13cb0dd0beef157df955bf9
