### ISSUE TITLE
Request New converters

### ISSUE THREAD

**Issue by ejaronne** [mitre/heimdall_tools#23]
Requesting new converters, in rough order of priority:
1. Burp Suite Pro (likely their xml output)
2. Nessus (Vulnerability scan - CVE and least functionality (SI-2, RA-5))
3. Nikto (Dynamic Code Analysis software)
4. NetSparker
5. Sneak (package dependency checker (CVE))

**Comment by rx294** [comment]
closing this issue as it was separated to issues #28 #29 #30 #31 #32 
as per @aaronlippold  request
