### ISSUE TITLE
Unable to Convert Fortify 19.2.0 FVDL file to HDF

### ISSUE THREAD

**Issue by dornered** [mitre/heimdall_tools#25]
I am trying to use Heimdall Tools to convert a Fortify FVDL file to HDF format json to be viewable in Heimdall.  However, I am receiving the following error:  "Invalid Fortify FVDL file provided Exception: undefined method 'new' for Nori:Module (RuntimeError)".  I opened the FVDL file and it is a valid XML file.  The FVDL file was created with Fortify version 19.2.0.

The complete output is listed below:
`heimdall_tools fortify_mapper -f gopax.fvdl -o fortify-heimdall-results.json
Traceback (most recent call last):
        10: from /home/edorner/.rbenv/versions/2.7.0/bin/heimdall_tools:23:in `<main>'
         9: from /home/edorner/.rbenv/versions/2.7.0/bin/heimdall_tools:23:in `load'
         8: from /home/edorner/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/heimdall_tools-1.2.0/exe/heimdall_tools:14:in `<top (required)>'
         7: from /home/edorner/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
         6: from /home/edorner/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/heimdall_tools-1.2.0/lib/heimdall_tools/command.rb:46:in `dispatch'
         5: from /home/edorner/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
         4: from /home/edorner/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
         3: from /home/edorner/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
         2: from /home/edorner/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/heimdall_tools-1.2.0/lib/heimdall_tools/cli.rb:11:in `fortify_mapper'
         1: from /home/edorner/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/heimdall_tools-1.2.0/lib/heimdall_tools/cli.rb:11:in `new'
/home/edorner/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/heimdall_tools-1.2.0/lib/heimdall_tools/fortify_mapper.rb:14:in `initialize': undefined method `new' for Nori:Module (NoMethodError)
        11: from /home/edorner/.rbenv/versions/2.7.0/bin/heimdall_tools:23:in `<main>'
        10: from /home/edorner/.rbenv/versions/2.7.0/bin/heimdall_tools:23:in `load'
         9: from /home/edorner/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/heimdall_tools-1.2.0/exe/heimdall_tools:14:in `<top (required)>'
         8: from /home/edorner/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
         7: from /home/edorner/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/heimdall_tools-1.2.0/lib/heimdall_tools/command.rb:46:in `dispatch'
         6: from /home/edorner/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
         5: from /home/edorner/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
         4: from /home/edorner/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
         3: from /home/edorner/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/heimdall_tools-1.2.0/lib/heimdall_tools/cli.rb:11:in `fortify_mapper'
         2: from /home/edorner/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/heimdall_tools-1.2.0/lib/heimdall_tools/cli.rb:11:in `new'
         1: from /home/edorner/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/heimdall_tools-1.2.0/lib/heimdall_tools/fortify_mapper.rb:13:in `initialize'
/home/edorner/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/heimdall_tools-1.2.0/lib/heimdall_tools/fortify_mapper.rb:20:in `rescue in initialize': Invalid Fortify FVDL file provided Exception: undefined method `new' for Nori:Module (RuntimeError)`

**Comment by rx294** [comment]
Hello @dornered thank you reporting this issue.
