### ISSUE TITLE
Ruby 2.7 produces deprecated code warnings

### ISSUE THREAD

**Issue by jsa5593** [mitre/heimdall_tools#48]
When running heimdall_tools zap_mapper through docker there were some warnings due to deprecated code. The command still executed properly.

**Comment by rx294** [comment]
Thank for the note @jsa5593 are working on fixing the packaging now to resolve this issue.

**Comment by rbclark** [comment]
Based on the latest output of the CI results, this no longer seems to be the case: https://github.com/mitre/heimdall_tools/runs/2632780627
