### ISSUE TITLE
Add '--input / -i' as options and clean up documentation

### ISSUE THREAD

**Issue by Amndeep7** [mitre/heimdall_tools#98]
Instead of doing `-x` or `-j` or whatever, just simplify the situation and add/recommend `-i` since there are no other input files (though there are occasionally other arguments/options, but none of them use `-i`).  First step would be to add the two as additional aliases to whatever's already there, and then in a later major version bump we can drop support for all the non `i` ones.

Also, the documentation needs to be cleaned up/improved in several regards: use the `banner` option from thor, clean up the english, sometimes it says `--option_prefix` even though it ought to be `--option`, etc.

**Comment by Bialogs** [comment]
I don't see us breaking compatibility with users existing workflows as a high priority. I understand the desire to simplify the interface but maybe there was little consideration given to existing users.
